# Generated by Django 6.1 on 2026-09-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='WORKS_RECOMMENDED',
        ),
    ]
