# Generated by Django 6.1 on 2026-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MOSPI_ADMIN', 'MoSPI Admin'), ('STATE_NODAL', 'State Nodal Authority'), ('MP', 'Member of Parliament'), ('DISTRICT_AUTHORITY', 'District Authority')], default='DISTRICT_AUTHORITY', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(help_text='e.g. MOSPI-001, STA-012, MP-045, DIST-008', max_length=20, unique=True),
        ),
    ]
