# Generated by Django 6.1 on 2026-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_nominated_mp',
            field=models.BooleanField(default=False, help_text='Nominated MP with Pan-India jurisdiction'),
        ),
    ]
