# Generated by Django 6.1 on 2026-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_nominated_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State / UT for elected MPs or State Nodal officers', max_length=100, null=True),
        ),
    ]
