# Generated by Django 6.1 on 2026-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurisdictions', '0002_seed_mplads_jurisdictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisdiction',
            name='level',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='jurisdiction_type',
            field=models.CharField(blank=True, choices=[('STATE', 'State / UT'), ('DISTRICT', 'District')], default='DISTRICT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
